// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "desgruppe/internal/entities"

import "desgruppe/internal/templ/views/components"

type UserLayoutProps struct {
	Title   string
	Cart    UserCart
	Styles  []string
	Scripts []string
}

type UserCart struct {
	Products []entities.Product
	Colors   []string
	Qtys     []int
	ExRate   float64
}

func UserPageLayout(props UserLayoutProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"yandex-verification\" content=\"034d2326f768b4cc\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"description\" content=\"Сайт компании desGruppe посвящён дизайнерским предметам интерьера: эксклюзивная мебель, оригинальные светильники, великолепные раковины и зеркала из бронзы, стулья, диваны для дома и офиса, красочные и деловые. Индивидуальные дизайн-проекты позволят вам воплотить любую мечту интерьера в жизнь\"><meta http-equiv=\"keywords\" content=\"мебель, дизайн-проект, светильники, раковины, зеркала, бронза, интерьер\"><meta property=\"og:title\" content=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(props.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/layout/user-layout.templ`, Line: 30, Col: 49}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/layout/user-layout.templ`, Line: 31, Col: 23}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</title><link rel=\"icon\" href=\"imgs/favicon.ico\" type=\"image/icon\"><link rel=\"shortcut icon\" href=\"imgs/favicon.ico\" type=\"image/icon\"><link rel=\"stylesheet\" href=\"/static/style/header-style.css\"><link rel=\"stylesheet\" href=\"../../static/style/shop-item-style.css\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, st := range props.Styles {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<link rel=\"stylesheet\" href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("../../static/style/" + st)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/layout/user-layout.templ`, Line: 37, Col: 60}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</head><body class=\"body\"><header class=\"header\"><div class=\"header-title\"><a href=\"/\" class=\"header-logo-a\"><span class=\"header-logo-main\">desGruppe</span> <span class=\"header-logo-text\">Дизайнерские предметы интерьера</span></a><div class=\"header-title-panel\"><div class=\"header-search-container\"><input type=\"text\" class=\"header-search-input\" placeholder=\"Поиск\"> <button class=\"header-search-button\"><img src=\"imgs/icons/search-icon.png\" alt=\"\" class=\"header-search-button-img\"></button></div><a class=\"header-cart-container\"><img src=\"imgs/icons/cart-icon.png\" alt=\"\" class=\"header-cart-img\"> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(props.Cart.Products) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"header-cart-cnt\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div class=\"header-cart-cnt\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(Sum(props.Cart.Qtys))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/layout/user-layout.templ`, Line: 59, Col: 59}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</a><div class=\"header-burger-container\"><img src=\"imgs/icons/burger-menu-icon.png\" alt=\"\" class=\"header-burger-img\"></div></div></div><nav class=\"header-nav\"><ul class=\"header-nav-ul\"><li class=\"header-nav-li\"><a href=\"/furniture\" class=\"header-nav-a\">Мебель</a></li><li class=\"header-nav-li\"><a href=\"/light\" class=\"header-nav-a\">Свет</a></li><li class=\"header-nav-li\"><a href=\"/interior\" class=\"header-nav-a\">Аксессуары</a></li><li class=\"header-nav-li\"><a href=\"/designers\" class=\"header-nav-a\">Дизайнеры</a></li><li class=\"header-nav-li\"><a href=\"/producers\" class=\"header-nav-a\">Фабрики</a></li><li class=\"header-nav-li\"><a href=\"/available\" class=\"header-nav-a\">Наличие</a></li><li class=\"header-nav-li\"><a href=\"/contacts\" class=\"header-nav-a\">Контакты</a></li></ul></nav></header><main class=\"main\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</main><footer class=\"footer\"><div class=\"footer-block\"><div class=\"footer-contacts-container\"><div class=\"footer-contacts\"><a href=\"tel:+74957613505\" class=\"footer-contact\">+7 495 761-35-05</a> <a href=\"mailto:info@desgruppe.ru\" class=\"footer-contact\">info@desgruppe.ru</a></div><p class=\"footer-hours\">Пн - Пт 9:00 - 19:00</p><a href=\"/contacts\" class=\"footer-contact-us\">Напишите нам</a></div><nav class=\"footer-nav\"><a href=\"/about\" class=\"footer-nav-a\">О компании</a> <a href=\"/terms\" class=\"footer-nav-a\">Условия покупки</a></nav></div><div class=\"footer-block footer-block-colophon\"><div class=\"footer-colophon-container\"><a href=\"/\" class=\"footer-home-link\">desGruppe.shop</a><p class=\"footer-colophon\">© 2025 desgruppe дизайнерские предметы интерьера</p><a href=\"/personal-data\" class=\"footer-terms-link\">Согласие на обработку <br>персональных данных</a></div><div class=\"footer-social-container\"><a href=\"https://vk.com\" class=\"footer-social-a\"><img src=\"imgs/icons/vk-black-icon.png\" alt=\"\" class=\"footer-social-icon\"></a></div></div></footer><div class=\"cart-bg hidden\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.CartPanel(props.Cart.Products, props.Cart.Colors, props.Cart.Qtys, props.Cart.ExRate).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, sc := range props.Scripts {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<script src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs("/script/user/" + sc)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/layout/user-layout.templ`, Line: 114, Col: 38}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\" defer></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<script src=\"/script/user/adaptive.js\"></script><script src=\"/script/user/cart.js\" defer></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Sum(ints []int) int {
	r := 0
	for _, i := range ints {
		r += i
	}
	return r
}

var _ = templruntime.GeneratedTemplate
