// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AdminModulePanel() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"panel\"><h2 class=\"panel-title\">Модули</h2><ul class=\"panel-ul\"><li class=\"panel-li\"><a href=\"/admin/sections\" class=\"panel-a\">Разделы</a></li><li class=\"panel-li\"><a href=\"/admin/colors\" class=\"panel-a\">Цвета</a></li><li class=\"panel-li\" style=\"color: black\"><a href=\"/admin/products\" class=\"panel-a\" style=\"color: black\">Изделия</a></li><li class=\"panel-li\"><a href=\"/admin/designers\" class=\"panel-a\">Дизайнеры</a></li><li class=\"panel-li\"><a href=\"/admin/producers\" class=\"panel-a\">Производители</a></li><li class=\"panel-empty-li\"></li><li class=\"panel-li\"><a href=\"/admin/sales\" class=\"panel-a\">Распродажи</a></li><li class=\"panel-li\"><a href=\"/admin/available\" class=\"panel-a\">Наличие</a></li><li class=\"panel-empty-li\"></li><li class=\"panel-li\"><a href=\"/admin/orders\" class=\"panel-a\">Заказы</a></li><li class=\"panel-li\"><a href=\"/admin/questions\" class=\"panel-a\">Вопросы</a></li><li class=\"panel-empty-li\"></li><li class=\"panel-li\"><a href=\"/admin/exchange-rate\" class=\"panel-a\">Курс валюты</a></li></ul></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
