// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"desgruppe/internal/entities"
	"fmt"
	"github.com/dustin/go-humanize"
	"strings"
)

type NotificationMailProps struct {
	Order
	Products []entities.Product
	Colors   []string
	Qtys     []int
	ExRate   float64
}

type Order struct {
	Name    string
	Date    string
	Comment string
	Phone   string
	Email   string
}

func NotificationMail(props NotificationMailProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Desgruppe order</title></head><body><div class=\"add-container\"><h2 class=\"add-title\" style=\"margin-bottom: 12px;\">Заказ</h2><div class=\"add-form\"><div class=\"add-form-block\" style=\"display: flex;\"><p class=\"add-form-label\">Контактное лицо</p><p class=\"add-form-p add-name\" style=\"margin-left: 12px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(props.Order.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/pages/admin/mail.templ`, Line: 40, Col: 82}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</p></div><div class=\"add-form-block\" style=\"display: flex;\"><p class=\"add-form-label\">Дата</p><p class=\"add-form-p add-comment\" style=\"margin-left: 12px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.Order.Date)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/pages/admin/mail.templ`, Line: 44, Col: 85}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p></div><div class=\"add-form-block\" style=\"display: flex;\"><p class=\"add-form-label\">Телефон</p><p class=\"add-form-p add-phone\" style=\"margin-left: 12px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(props.Order.Phone)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/pages/admin/mail.templ`, Line: 48, Col: 84}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p></div><div class=\"add-form-block\" style=\"display: flex;\"><p class=\"add-form-label\">Эл. почта</p><p class=\"add-form-p add-email\" style=\"margin-left: 12px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(props.Order.Email)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/pages/admin/mail.templ`, Line: 52, Col: 84}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</p></div><div class=\"add-form-block\" style=\"display: flex;\"><p class=\"add-form-label\">Комментарий</p><p class=\"add-form-p add-comment\" style=\"margin-left: 12px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(props.Order.Comment)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/pages/admin/mail.templ`, Line: 56, Col: 88}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</p></div></div><div class=\"add-form\"><h3 class=\"add-title\">Корзина</h3><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse:collapse; table-layout:fixed;\"><thead><tr><th align=\"left\" style=\"width:25%; padding: 12px 8px; background:#f4f4f4; font-size:20px; font-weight:bold; border-bottom:1px solid #ddd;\">Товар</th><th align=\"left\" style=\"width:25%; padding: 12px 8px; background:#f4f4f4; font-size:20px; font-weight:bold; border-bottom:1px solid #ddd;\">Цена</th><th align=\"left\" style=\"width:25%; padding: 12px 8px; background:#f4f4f4; font-size:20px; font-weight:bold; border-bottom:1px solid #ddd;\">Кол-во</th><th align=\"left\" style=\"width:25%; padding: 12px 8px; background:#f4f4f4; font-size:20px; font-weight:bold; border-bottom:1px solid #ddd;\">Итог</th></tr></thead> <tbody>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for i, pr := range props.Products {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<tr><td style=\"width:25%; padding: 10px 8px; border-bottom:1px solid #eee; font-size:16px;\"><div class=\"citems-elem-name\"><div class=\"citems-elem-name-container\"><p class=\"citems-elem-name-text\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(pr.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/pages/admin/mail.templ`, Line: 76, Col: 54}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</p><p style=\"font-size: 14px;\">Цвет: </p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(props.Colors) > 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<p style=\"padding-left: 12px; font-size:12px;\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var8 string
				templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(props.Colors[i])
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/pages/admin/mail.templ`, Line: 79, Col: 77}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<p style=\"padding-left: 12px; font-size:12px;\">Цвет не найден</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div></div></td><td style=\"width:25%; padding: 10px 8px; border-bottom:1px solid #eee; font-size:16px;\"><p class=\"citem-elem-price-rub\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(FormatPrice(float64(pr.Price) * props.ExRate))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/pages/admin/mail.templ`, Line: 87, Col: 87}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " ₽</p></td><td style=\"width:25%; padding: 10px 8px; border-bottom:1px solid #eee; font-size:16px;\"><div class=\"citems-elem-qty-container\"><div class=\"citem-elem-qty\"><div class=\"citem-elem-qty-cnt\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(props.Qtys[i])
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/pages/admin/mail.templ`, Line: 92, Col: 59}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</div></div></div></td><td style=\"width:25%; padding: 10px 8px; border-bottom:1px solid #eee; font-size:16px;\"><p class=\"citem-elem-total-rub\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(FormatPrice(float64(props.Qtys[i]) * float64(pr.Price) * props.ExRate))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/pages/admin/mail.templ`, Line: 97, Col: 110}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, " ₽</p></td></tr>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</tbody><tfoot><tr><td style=\"width:25%; padding: 10px 8px;\"></td><td style=\"width:25%; padding: 10px 8px;\"></td><td style=\"width:25%; padding: 10px 8px;\"></td><td style=\"width:25%; padding: 10px 8px; font-weight:bold; font-size:18px;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var12 string
		templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(FormatPrice(CountTotal(props.Products, props.Qtys, props.ExRate) - CountTotalSale(props.Products, props.Qtys, props.ExRate)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `desgruppe prod/internal/templ/views/pages/admin/mail.templ`, Line: 107, Col: 208}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, " ₽</td></tr></tfoot></table></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func CountTotal(products []entities.Product, qtys []int, exRate float64) float64 {
	res := 0.0
	for i, pr := range products {
		res += float64(pr.Price) * float64(qtys[i]) * exRate
	}
	return res
}
func CountTotalSale(products []entities.Product, qtys []int, exRate float64) float64 {
	res := 0.0
	for i, pr := range products {
		res += float64(pr.Price) * float64(qtys[i]) * exRate * float64(pr.Sale/100)
	}
	return res
}

func FormatPrice(value float64) string {
	// humanize добавляет запятые, заменяем на пробелы
	intStr := humanize.Commaf(float64(int64(value)))
	intStr = strings.ReplaceAll(intStr, ",", " ")
	frac := value - float64(int64(value))
	return fmt.Sprintf("%s.%02d", intStr, int64(frac*100))
}

var _ = templruntime.GeneratedTemplate
